#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));


//Autoloader de Composer, para cargar las dependencias del proyecto.
require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

// Kernel de Artisan, para manejar los comandos de la consola.
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

// Ejecutar el comando de Artisan, pasando los argumentos de la línea de comandos.
$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

// Terminar el kernel de Artisan, limpiando cualquier recurso utilizado.
$kernel->terminate($input, $status);

exit($status);